/* generated by Codename Lang; schema lang.c17/0 */
/* Moves below are authority transitions; C value assignment makes no ABI or zero-copy claim. */
/* call-boundary attribute set: EMPTY (0 entries). Per D-11-09, cgen.emitCall never mints an optimizer-visible alias or capture attribute at any Lang-to-Lang call boundary this phase -- NAT-05 is satisfied by this explicit, generated empty set, not by silence. */
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char *lang_invocations[] = {
  "inv:entry:s1:phase11.multi_function_gate_corpus:fn:main",
  "inv:entry:s1:phase11.multi_function_gate_corpus:fn:main/s1:phase11.multi_function_gate_corpus:fn:main:op:0#0",
};

static const unsigned int lang_child_index_LANG_S1_PHASE11_MULTI_FUNCTION_GATE_CORPUS_FN_MAIN_OP_0[] = {
  1u,
  0u,
};

typedef struct LANG_BUFFER {
  unsigned char bytes[4];
  size_t length;
} LANG_BUFFER;

#define LANG_OUTPUT_LIMIT 16777216u
#define LANG_EVENT_CAPACITY 3u

typedef struct LANG_EVENT {
  const char *kind;
  const char *id;
  const char *function_id;
  const char *source_place;
  const char *target_place;
  const char *type_id;
  const char *invocation;
  const char *callee_function_id;
} LANG_EVENT;

static LANG_EVENT lang_events[LANG_EVENT_CAPACITY];
static size_t lang_event_count = 0u;
static size_t lang_output_count = 0u;

static int lang_write_bytes(const char *data, size_t length) {
  if (length > LANG_OUTPUT_LIMIT - lang_output_count) return 0;
  if (length != 0u && fwrite(data, 1u, length, stdout) != length) return 0;
  lang_output_count += length;
  return 1;
}

static int lang_write_literal(const char *value) {
  return lang_write_bytes(value, strlen(value));
}

static int lang_write_json_string(const char *value) {
  static const char hex[] = "0123456789abcdef";
  if (!lang_write_bytes("\"", 1u)) return 0;
  for (; *value != '\0'; value++) {
    unsigned char byte = (unsigned char)*value;
    const char *escape = NULL;
    if (byte == '"') escape = "\\\"";
    else if (byte == '\\') escape = "\\\\";
    else if (byte == '\b') escape = "\\b";
    else if (byte == '\f') escape = "\\f";
    else if (byte == '\n') escape = "\\n";
    else if (byte == '\r') escape = "\\r";
    else if (byte == '\t') escape = "\\t";
    if (escape != NULL) { if (!lang_write_literal(escape)) return 0; }
    else if (byte < 0x20u) {
      char encoded[6] = {'\\', 'u', '0', '0', hex[byte >> 4u], hex[byte & 0x0fu]};
      if (!lang_write_bytes(encoded, sizeof encoded)) return 0;
    } else if (!lang_write_bytes(value, 1u)) return 0;
  }
  return lang_write_bytes("\"", 1u);
}

static int lang_record_event(const char *kind, const char *id, const char *function_id, const char *source_place, const char *target_place, const char *type_id, const char *invocation, const char *callee_function_id) {
  if (lang_event_count >= LANG_EVENT_CAPACITY) return 0;
  lang_events[lang_event_count++] = (LANG_EVENT){kind, id, function_id, source_place, target_place, type_id, invocation, callee_function_id};
  return 1;
}

static int lang_write_events(void) {
  size_t index;
  for (index = 0u; index < lang_event_count; index++) {
    const LANG_EVENT *event = &lang_events[index];
    if (index != 0u && !lang_write_bytes(",", 1u)) return 0;
    if (!lang_write_literal("{\"schema\":\"lang.execution/2\",\"id\":") || !lang_write_json_string(event->id)) return 0;
    if (!lang_write_literal(",\"kind\":") || !lang_write_json_string(event->kind)) return 0;
    if (!lang_write_literal(",\"function_id\":") || !lang_write_json_string(event->function_id)) return 0;
    if (event->source_place != NULL && (!lang_write_literal(",\"source_place\":") || !lang_write_json_string(event->source_place))) return 0;
    if (event->target_place != NULL && (!lang_write_literal(",\"target_place\":") || !lang_write_json_string(event->target_place))) return 0;
    if (event->type_id != NULL && (!lang_write_literal(",\"type_id\":") || !lang_write_json_string(event->type_id))) return 0;
    if (!lang_write_literal(",\"invocation\":") || !lang_write_json_string(event->invocation)) return 0;
    if (event->callee_function_id != NULL && (!lang_write_literal(",\"callee_function_id\":") || !lang_write_json_string(event->callee_function_id))) return 0;
    if (!lang_write_bytes("}", 1u)) return 0;
  }
  return 1;
}

static int lang_write_buffer_hex(const LANG_BUFFER *value) {
  static const char hex[] = "0123456789abcdef";
  size_t index;
  if (value->length > sizeof value->bytes) return 0;
  for (index = 0u; index < value->length; index++) {
    char encoded[2] = {hex[value->bytes[index] >> 4u], hex[value->bytes[index] & 0x0fu]};
    if (!lang_write_bytes(encoded, sizeof encoded)) return 0;
  }
  return 1;
}

static int lang_write_byte(unsigned char value) {
  char encoded[3];
  int length = snprintf(encoded, sizeof encoded, "%u", (unsigned int)value);
  return length > 0 && (size_t)length < sizeof encoded && lang_write_bytes(encoded, (size_t)length);
}

static int lang_write_live_resources(void) {
  return lang_write_literal("[]");
}

static LANG_BUFFER LANG_TOUCH(LANG_BUFFER, unsigned int);
static unsigned char LANG_MAIN(unsigned char, unsigned int);
static unsigned char LANG_IDENTITY(unsigned char, unsigned int);

static LANG_BUFFER LANG_TOUCH(LANG_BUFFER lang_value_buffer, unsigned int invocation_index) {
  (void)invocation_index;
  LANG_BUFFER lang_value_first = lang_value_buffer; /* exclusive borrow representation: s1:phase11.multi_function_gate_corpus:fn:touch:op:0 */
  (void)lang_value_first;
  if (!lang_record_event("value.borrowed_exclusive", "s1:phase11.multi_function_gate_corpus:fn:touch:op:0:event", "s1:phase11.multi_function_gate_corpus:fn:touch", "s1:phase11.multi_function_gate_corpus:fn:touch:place:0", "s1:phase11.multi_function_gate_corpus:fn:touch:place:1", "s1:phase11.multi_function_gate_corpus:fn:touch:type:0", lang_invocations[invocation_index], NULL)) abort();
  LANG_BUFFER lang_value_second = lang_value_first; /* shared borrow representation: s1:phase11.multi_function_gate_corpus:fn:touch:op:1 */
  (void)lang_value_second;
  if (!lang_record_event("value.borrowed", "s1:phase11.multi_function_gate_corpus:fn:touch:op:1:event", "s1:phase11.multi_function_gate_corpus:fn:touch", "s1:phase11.multi_function_gate_corpus:fn:touch:place:1", "s1:phase11.multi_function_gate_corpus:fn:touch:place:2", "s1:phase11.multi_function_gate_corpus:fn:touch:type:0", lang_invocations[invocation_index], NULL)) abort();
  LANG_BUFFER lang_value_third = lang_value_second; /* shared borrow representation: s1:phase11.multi_function_gate_corpus:fn:touch:op:2 */
  (void)lang_value_third;
  if (!lang_record_event("value.borrowed", "s1:phase11.multi_function_gate_corpus:fn:touch:op:2:event", "s1:phase11.multi_function_gate_corpus:fn:touch", "s1:phase11.multi_function_gate_corpus:fn:touch:place:2", "s1:phase11.multi_function_gate_corpus:fn:touch:place:3", "s1:phase11.multi_function_gate_corpus:fn:touch:type:0", lang_invocations[invocation_index], NULL)) abort();
  if (!lang_record_event("function.returned", "s1:phase11.multi_function_gate_corpus:fn:touch:op:3:event:returned", "s1:phase11.multi_function_gate_corpus:fn:touch", "s1:phase11.multi_function_gate_corpus:fn:touch:place:3", NULL, "s1:phase11.multi_function_gate_corpus:fn:touch:type:0", lang_invocations[invocation_index], NULL)) abort(); /* returned place: s1:phase11.multi_function_gate_corpus:fn:touch:op:3 */
  return lang_value_third;
}

static unsigned char LANG_MAIN(unsigned char lang_value_value, unsigned int invocation_index) {
  (void)invocation_index;
  if (!lang_record_event("function.called", "s1:phase11.multi_function_gate_corpus:fn:main:op:0:event:called", "s1:phase11.multi_function_gate_corpus:fn:main", "s1:phase11.multi_function_gate_corpus:fn:main:place:0", "s1:phase11.multi_function_gate_corpus:fn:main:place:1", "s1:phase11.multi_function_gate_corpus:fn:main:type:0", lang_invocations[invocation_index], "s1:phase11.multi_function_gate_corpus:fn:identity")) abort();
  unsigned char lang_value_result = LANG_IDENTITY(lang_value_value, lang_child_index_LANG_S1_PHASE11_MULTI_FUNCTION_GATE_CORPUS_FN_MAIN_OP_0[invocation_index]); /* call: s1:phase11.multi_function_gate_corpus:fn:main:op:0 */
  (void)lang_value_result;
  if (!lang_record_event("function.returned", "s1:phase11.multi_function_gate_corpus:fn:main:op:1:event:returned", "s1:phase11.multi_function_gate_corpus:fn:main", "s1:phase11.multi_function_gate_corpus:fn:main:place:1", NULL, "s1:phase11.multi_function_gate_corpus:fn:main:type:0", lang_invocations[invocation_index], NULL)) abort(); /* returned place: s1:phase11.multi_function_gate_corpus:fn:main:op:1 */
  return lang_value_result;
}

static unsigned char LANG_IDENTITY(unsigned char lang_value_value, unsigned int invocation_index) {
  (void)invocation_index;
  if (!lang_record_event("function.returned", "s1:phase11.multi_function_gate_corpus:fn:identity:op:0:event:returned", "s1:phase11.multi_function_gate_corpus:fn:identity", "s1:phase11.multi_function_gate_corpus:fn:identity:place:0", NULL, "s1:phase11.multi_function_gate_corpus:fn:identity:type:0", lang_invocations[invocation_index], NULL)) abort(); /* returned place: s1:phase11.multi_function_gate_corpus:fn:identity:op:0 */
  return lang_value_value;
}

int main(int argc, char **argv) {
  (void)lang_invocations;
  (void)lang_record_event;
  (void)LANG_TOUCH;
  (void)LANG_MAIN;
  (void)LANG_IDENTITY;
  (void)lang_write_buffer_hex;
  (void)lang_write_byte;
  if (argc != 2) return 64;
  if (strcmp(argv[1], "7") != 0) return 65;
  unsigned char lang_entry_input = 7u;
  unsigned char lang_entry_output = LANG_MAIN(lang_entry_input, 0u);
  if (!lang_write_literal("{\"schema\":\"lang.execution/2\",\"outcome\":{\"kind\":\"returned\",\"value\":\"")) return 74;
  if (!lang_write_byte(lang_entry_output)) return 74;
  if (!lang_write_literal("\"},\"events\":[")) return 74;
  if (!lang_write_events()) return 74;
  if (!lang_write_literal("],\"live_resources\":")) return 74;
  if (!lang_write_live_resources()) return 74;
  if (!lang_write_literal("}\n")) return 74;
  return 0;
}
