package cgen

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"github.com/codename-lang/lang/internal/compiler/core"
	"github.com/codename-lang/lang/internal/compiler/corevalidate"
	"github.com/codename-lang/lang/internal/compiler/execution"
)

const Schema = "lang.c17/0"

func Emit(program core.Program) (string, error) {
	validated := corevalidate.Validate(program)
	if !validated.Valid {
		return "", fmt.Errorf("core validation failed: %s", validated.Problems[0].Code)
	}
	program = validated.Program()
	if len(program.Functions) != 1 {
		return "", fmt.Errorf("C emitter expects one function")
	}
	if program.Functions[0].Linear != nil {
		return emitLinear(program.Functions[0])
	}
	return emitMatch(program, false)
}

// EmitNative keeps the Phase 1 evidence bytes frozen while selecting the
// single-document execution protocol required at the child-process boundary.
func EmitNative(program core.Program) (string, error) {
	validated := corevalidate.Validate(program)
	if !validated.Valid {
		return "", fmt.Errorf("core validation failed: %s", validated.Problems[0].Code)
	}
	program = validated.Program()
	if len(program.Functions) != 1 {
		return "", fmt.Errorf("C emitter expects one function")
	}
	if program.Functions[0].Linear != nil {
		return emitLinear(program.Functions[0])
	}
	return emitMatch(program, true)
}

func emitMatch(program core.Program, executionJSON bool) (string, error) {
	if len(program.DataTypes) != 1 {
		return "", fmt.Errorf("match C emitter expects one data type")
	}
	dataType := program.DataTypes[0]
	function := program.Functions[0]
	if len(dataType.Alternatives) == 0 {
		return "", fmt.Errorf("S1 C emitter requires alternatives")
	}

	var out strings.Builder
	out.WriteString("/* generated by Codename Lang; schema lang.c17/0 */\n")
	out.WriteString("#include <stdio.h>\n#include <string.h>\n\n")
	fmt.Fprintf(&out, "typedef enum %s {\n", cName(dataType.Name))
	for index, alternative := range dataType.Alternatives {
		fmt.Fprintf(&out, "  %s_%s = %d,\n", cName(dataType.Name), cName(alternative), index)
	}
	fmt.Fprintf(&out, "} %s;\n\n", cName(dataType.Name))
	fmt.Fprintf(&out, "static %s %s(%s %s) {\n", cName(function.ReturnType), cName(function.Name), cName(function.Parameter.Type), cName(function.Parameter.Name))
	fmt.Fprintf(&out, "  switch (%s) {\n", cName(function.Parameter.Name))
	for _, arm := range function.Match.Arms {
		fmt.Fprintf(&out, "    case %s_%s: return %s_%s;\n", cName(dataType.Name), cName(arm.Pattern), cName(dataType.Name), cName(arm.Value))
	}
	out.WriteString("  }\n  return (int)255; /* invalid safe-language tag: fail in main */\n}\n\n")
	fmt.Fprintf(&out, "static const char *%s_name(%s value) {\n  switch (value) {\n", cName(dataType.Name), cName(dataType.Name))
	for _, alternative := range dataType.Alternatives {
		fmt.Fprintf(&out, "    case %s_%s: return \"%s\";\n", cName(dataType.Name), cName(alternative), alternative)
	}
	out.WriteString("  }\n  return NULL;\n}\n\n")
	out.WriteString("int main(int argc, char **argv) {\n  if (argc != 2) return 64;\n")
	fmt.Fprintf(&out, "  %s input;\n", cName(dataType.Name))
	for index, alternative := range dataType.Alternatives {
		prefix := "if"
		if index > 0 {
			prefix = "else if"
		}
		fmt.Fprintf(&out, "  %s (strcmp(argv[1], \"%s\") == 0) input = %s_%s;\n", prefix, alternative, cName(dataType.Name), cName(alternative))
	}
	out.WriteString("  else return 65;\n")
	fmt.Fprintf(&out, "  %s output = %s(input);\n", cName(dataType.Name), cName(function.Name))
	fmt.Fprintf(&out, "  const char *name = %s_name(output);\n", cName(dataType.Name))
	if !executionJSON {
		out.WriteString("  if (name == NULL) return 70;\n  printf(\"%s\\n\", name);\n  return 0;\n}\n")
		return out.String(), nil
	}
	out.WriteString("  if (name == NULL) return 70;\n")
	for index, arm := range function.Match.Arms {
		prefix := "if"
		if index > 0 {
			prefix = "else if"
		}
		document := execution.Execution{
			Schema:  execution.Schema0,
			Outcome: execution.Outcome{Kind: "returned", Value: arm.Value},
			Events: []execution.Event{{
				Schema: execution.Schema0, ID: arm.ID + ":event:returned", Kind: "function.returned",
				FunctionID: function.ID, Input: arm.Pattern, Output: arm.Value,
			}},
			LiveResources: []string{},
		}
		encoded, err := json.Marshal(document)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&out, "  %s (strcmp(argv[1], %s) == 0) puts(%s);\n", prefix, strconv.Quote(arm.Pattern), strconv.Quote(string(encoded)))
	}
	out.WriteString("  else return 71;\n  return 0;\n}\n")
	return out.String(), nil
}

func emitLinear(function core.Function) (string, error) {
	input, initializer, typeName, err := linearInput(function)
	if err != nil {
		return "", err
	}
	document, err := linearExecution(function, input)
	if err != nil {
		return "", err
	}
	encoded, err := json.Marshal(document)
	if err != nil {
		return "", err
	}
	places := make(map[string]core.Place, len(function.Linear.Places))
	for _, place := range function.Linear.Places {
		places[place.ID] = place
	}
	parameter, ok := places[function.Parameter.ID]
	if !ok {
		return "", fmt.Errorf("linear parameter place is absent")
	}

	var out strings.Builder
	out.WriteString("/* generated by Codename Lang; schema lang.c17/0 */\n")
	out.WriteString("/* Moves below are authority transitions; C value assignment makes no ABI or zero-copy claim. */\n")
	out.WriteString("#include <stddef.h>\n#include <stdio.h>\n#include <string.h>\n\n")
	if function.Parameter.Type == "Buffer" {
		out.WriteString("typedef struct LANG_BUFFER {\n  unsigned char bytes[4];\n  size_t length;\n} LANG_BUFFER;\n\n")
	}
	out.WriteString("int main(int argc, char **argv) {\n")
	out.WriteString("  if (argc != 2) return 64;\n")
	fmt.Fprintf(&out, "  if (strcmp(argv[1], %s) != 0) return 65;\n", strconv.Quote(input))
	fmt.Fprintf(&out, "  %s %s = %s;\n", typeName, cLocal(parameter.Name), initializer)
	declared := map[string]bool{parameter.ID: true}
	for _, operation := range function.Linear.Operations {
		source := places[operation.SourceID]
		switch operation.Kind {
		case core.OpCopy, core.OpMove, core.OpBorrowShared:
			target, exists := places[operation.TargetID]
			if !exists || declared[operation.TargetID] {
				return "", fmt.Errorf("operation %q has invalid target", operation.ID)
			}
			label := "copy"
			if operation.Kind == core.OpMove {
				label = "authority transfer"
			} else if operation.Kind == core.OpBorrowShared {
				label = "shared borrow representation"
			}
			fmt.Fprintf(&out, "  %s %s = %s; /* %s: %s */\n", typeName, cLocal(target.Name), cLocal(source.Name), label, operation.ID)
			declared[operation.TargetID] = true
		case core.OpReturn:
			fmt.Fprintf(&out, "  (void)%s; /* returned place: %s */\n", cLocal(source.Name), operation.ID)
		default:
			return "", fmt.Errorf("operation %q has unknown kind %q", operation.ID, operation.Kind)
		}
	}
	fmt.Fprintf(&out, "  puts(%s);\n", strconv.Quote(string(encoded)))
	out.WriteString("  return 0;\n}\n")
	return out.String(), nil
}

func linearInput(function core.Function) (input, initializer, typeName string, err error) {
	switch function.Parameter.Type {
	case "Buffer":
		return "01020304", "{{1u, 2u, 3u, 4u}, 4u}", "LANG_BUFFER", nil
	case "Byte":
		return "7", "7u", "unsigned char", nil
	default:
		return "", "", "", fmt.Errorf("unsupported linear C type %q", function.Parameter.Type)
	}
}

func linearExecution(function core.Function, input string) (execution.Execution, error) {
	values := map[string]string{function.Parameter.ID: input}
	events := make([]execution.Event, 0, len(function.Linear.Operations))
	for _, operation := range function.Linear.Operations {
		value, ok := values[operation.SourceID]
		if !ok {
			return execution.Execution{}, fmt.Errorf("operation %q reads unavailable place", operation.ID)
		}
		switch operation.Kind {
		case core.OpCopy:
			values[operation.TargetID] = value
			events = append(events, linearEvent(function, operation, "value.copied"))
		case core.OpMove:
			delete(values, operation.SourceID)
			values[operation.TargetID] = value
			events = append(events, linearEvent(function, operation, "value.transferred"))
		case core.OpBorrowShared:
			values[operation.TargetID] = value
			events = append(events, linearEvent(function, operation, "value.borrowed"))
		case core.OpReturn:
			events = append(events, execution.Event{
				Schema: execution.Schema1, ID: operation.ID + ":event:returned", Kind: "function.returned",
				FunctionID: function.ID, SourcePlace: operation.SourceID, TypeID: operation.TypeID,
			})
			return execution.Execution{
				Schema: execution.Schema1, Outcome: execution.Outcome{Kind: "returned", Value: value},
				Events: events, LiveResources: []string{},
			}, nil
		}
	}
	return execution.Execution{}, fmt.Errorf("linear body has no return")
}

func linearEvent(function core.Function, operation core.LinearOperation, kind string) execution.Event {
	return execution.Event{
		Schema: execution.Schema1, ID: operation.ID + ":event", Kind: kind,
		FunctionID: function.ID, SourcePlace: operation.SourceID, TargetPlace: operation.TargetID, TypeID: operation.TypeID,
	}
}

func cName(name string) string {
	var out strings.Builder
	for _, r := range name {
		if r >= 'a' && r <= 'z' {
			out.WriteRune(r - ('a' - 'A'))
		} else if r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' {
			out.WriteRune(r)
		} else {
			out.WriteByte('_')
		}
	}
	return "LANG_" + out.String()
}

func cLocal(name string) string {
	var out strings.Builder
	out.WriteString("lang_value_")
	for _, r := range name {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' {
			out.WriteRune(r)
		} else {
			out.WriteByte('_')
		}
	}
	return out.String()
}
