package cgen

import (
	"fmt"
	"strings"

	"github.com/codename-lang/lang/internal/compiler/core"
)

const Schema = "lang.c17/0"

func Emit(program core.Program) (string, error) {
	if len(program.DataTypes) != 1 || len(program.Functions) != 1 {
		return "", fmt.Errorf("S1 C emitter expects one data type and one function")
	}
	dataType := program.DataTypes[0]
	function := program.Functions[0]
	if len(dataType.Alternatives) == 0 {
		return "", fmt.Errorf("S1 C emitter requires alternatives")
	}

	var out strings.Builder
	out.WriteString("/* generated by Codename Lang; schema lang.c17/0 */\n")
	out.WriteString("#include <stdio.h>\n#include <string.h>\n\n")
	fmt.Fprintf(&out, "typedef enum %s {\n", cName(dataType.Name))
	for index, alternative := range dataType.Alternatives {
		fmt.Fprintf(&out, "  %s_%s = %d,\n", cName(dataType.Name), cName(alternative), index)
	}
	fmt.Fprintf(&out, "} %s;\n\n", cName(dataType.Name))
	fmt.Fprintf(&out, "static %s %s(%s %s) {\n", cName(function.ReturnType), cName(function.Name), cName(function.Parameter.Type), cName(function.Parameter.Name))
	fmt.Fprintf(&out, "  switch (%s) {\n", cName(function.Parameter.Name))
	for _, arm := range function.Match.Arms {
		fmt.Fprintf(&out, "    case %s_%s: return %s_%s;\n", cName(dataType.Name), cName(arm.Pattern), cName(dataType.Name), cName(arm.Value))
	}
	out.WriteString("  }\n  return (int)255; /* invalid safe-language tag: fail in main */\n}\n\n")
	fmt.Fprintf(&out, "static const char *%s_name(%s value) {\n  switch (value) {\n", cName(dataType.Name), cName(dataType.Name))
	for _, alternative := range dataType.Alternatives {
		fmt.Fprintf(&out, "    case %s_%s: return \"%s\";\n", cName(dataType.Name), cName(alternative), alternative)
	}
	out.WriteString("  }\n  return NULL;\n}\n\n")
	out.WriteString("int main(int argc, char **argv) {\n  if (argc != 2) return 64;\n")
	fmt.Fprintf(&out, "  %s input;\n", cName(dataType.Name))
	for index, alternative := range dataType.Alternatives {
		prefix := "if"
		if index > 0 {
			prefix = "else if"
		}
		fmt.Fprintf(&out, "  %s (strcmp(argv[1], \"%s\") == 0) input = %s_%s;\n", prefix, alternative, cName(dataType.Name), cName(alternative))
	}
	out.WriteString("  else return 65;\n")
	fmt.Fprintf(&out, "  %s output = %s(input);\n", cName(dataType.Name), cName(function.Name))
	fmt.Fprintf(&out, "  const char *name = %s_name(output);\n", cName(dataType.Name))
	out.WriteString("  if (name == NULL) return 70;\n  printf(\"%s\\n\", name);\n  return 0;\n}\n")
	return out.String(), nil
}

func cName(name string) string {
	var out strings.Builder
	for _, r := range name {
		if r >= 'a' && r <= 'z' {
			out.WriteRune(r - ('a' - 'A'))
		} else if r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' {
			out.WriteRune(r)
		} else {
			out.WriteByte('_')
		}
	}
	return "LANG_" + out.String()
}
