/* generated by Codename Lang; schema lang.c17/0 */
/* Moves below are authority transitions; C value assignment makes no ABI or zero-copy claim. */
#include <stddef.h>
#include <stdio.h>
#include <string.h>

typedef enum LANG_SIGNAL {
  LANG_SIGNAL_LANG_GO = 0,
  LANG_SIGNAL_LANG_HALT = 1,
} LANG_SIGNAL;

#define LANG_OUTPUT_LIMIT 65536u
#define LANG_EVENT_CAPACITY 5u

typedef struct LANG_EVENT {
  const char *kind;
  const char *id;
  const char *function_id;
  const char *source_place;
  const char *target_place;
  const char *type_id;
} LANG_EVENT;

static LANG_EVENT lang_events[LANG_EVENT_CAPACITY];
static size_t lang_event_count = 0u;
static size_t lang_output_count = 0u;

static int lang_write_bytes(const char *data, size_t length) {
  if (length > LANG_OUTPUT_LIMIT - lang_output_count) return 0;
  if (length != 0u && fwrite(data, 1u, length, stdout) != length) return 0;
  lang_output_count += length;
  return 1;
}

static int lang_write_literal(const char *value) {
  return lang_write_bytes(value, strlen(value));
}

static int lang_write_json_string(const char *value) {
  static const char hex[] = "0123456789abcdef";
  if (!lang_write_bytes("\"", 1u)) return 0;
  for (; *value != '\0'; value++) {
    unsigned char byte = (unsigned char)*value;
    const char *escape = NULL;
    if (byte == '"') escape = "\\\"";
    else if (byte == '\\') escape = "\\\\";
    else if (byte == '\b') escape = "\\b";
    else if (byte == '\f') escape = "\\f";
    else if (byte == '\n') escape = "\\n";
    else if (byte == '\r') escape = "\\r";
    else if (byte == '\t') escape = "\\t";
    if (escape != NULL) { if (!lang_write_literal(escape)) return 0; }
    else if (byte < 0x20u) {
      char encoded[6] = {'\\', 'u', '0', '0', hex[byte >> 4u], hex[byte & 0x0fu]};
      if (!lang_write_bytes(encoded, sizeof encoded)) return 0;
    } else if (!lang_write_bytes(value, 1u)) return 0;
  }
  return lang_write_bytes("\"", 1u);
}

static int lang_record_event(const char *kind, const char *id, const char *function_id, const char *source_place, const char *target_place, const char *type_id) {
  if (lang_event_count >= LANG_EVENT_CAPACITY) return 0;
  lang_events[lang_event_count++] = (LANG_EVENT){kind, id, function_id, source_place, target_place, type_id};
  return 1;
}

static int lang_write_events(void) {
  size_t index;
  for (index = 0u; index < lang_event_count; index++) {
    const LANG_EVENT *event = &lang_events[index];
    if (index != 0u && !lang_write_bytes(",", 1u)) return 0;
    if (!lang_write_literal("{\"schema\":\"lang.execution/1\",\"id\":") || !lang_write_json_string(event->id)) return 0;
    if (!lang_write_literal(",\"kind\":") || !lang_write_json_string(event->kind)) return 0;
    if (!lang_write_literal(",\"function_id\":") || !lang_write_json_string(event->function_id)) return 0;
    if (event->source_place != NULL && (!lang_write_literal(",\"source_place\":") || !lang_write_json_string(event->source_place))) return 0;
    if (event->target_place != NULL && (!lang_write_literal(",\"target_place\":") || !lang_write_json_string(event->target_place))) return 0;
    if (event->type_id != NULL && (!lang_write_literal(",\"type_id\":") || !lang_write_json_string(event->type_id))) return 0;
    if (!lang_write_bytes("}", 1u)) return 0;
  }
  return 1;
}

#include <stdlib.h>

_Noreturn static void lang_defect(const char *reason) {
  (void)reason; /* D-04-15: no catch, no containment, no unwinding, no cleanup -- abort-only at the process root */
  abort();
}

int main(int argc, char **argv) {
  if (argc != 2) return 64;
  LANG_SIGNAL lang_value_flag;
  if (strcmp(argv[1], "Go") == 0) lang_value_flag = LANG_SIGNAL_LANG_GO;
  else if (strcmp(argv[1], "Halt") == 0) lang_value_flag = LANG_SIGNAL_LANG_HALT;
  else return 65;
  switch (lang_value_flag) {
    case LANG_SIGNAL_LANG_GO: {
      LANG_SIGNAL lang_value_flag_LANG_PLACE_1 = lang_value_flag; /* copy: s1:fallible.defect_terminal:fn:triage:op:0 */
      (void)lang_value_flag_LANG_PLACE_1;
      if (!lang_record_event("value.copied", "s1:fallible.defect_terminal:fn:triage:op:0:event", "s1:fallible.defect_terminal:fn:triage", "s1:fallible.defect_terminal:fn:triage:place:0", "s1:fallible.defect_terminal:fn:triage:place:1", "s1:fallible.defect_terminal:fn:triage:type:0")) return 74;
      LANG_SIGNAL lang_value_held = lang_value_flag_LANG_PLACE_1; /* authority transfer: s1:fallible.defect_terminal:fn:triage:op:1 */
      (void)lang_value_held;
      if (!lang_record_event("value.transferred", "s1:fallible.defect_terminal:fn:triage:op:1:event", "s1:fallible.defect_terminal:fn:triage", "s1:fallible.defect_terminal:fn:triage:place:1", "s1:fallible.defect_terminal:fn:triage:place:2", "s1:fallible.defect_terminal:fn:triage:type:0")) return 74;
      if (!lang_record_event("function.returned", "s1:fallible.defect_terminal:fn:triage:op:2:event:returned", "s1:fallible.defect_terminal:fn:triage", "s1:fallible.defect_terminal:fn:triage:place:2", NULL, "s1:fallible.defect_terminal:fn:triage:type:0")) return 74; /* returned place: s1:fallible.defect_terminal:fn:triage:op:2 */
      if (!lang_write_literal("{\"schema\":\"lang.execution/1\",\"outcome\":{\"kind\":\"returned\",\"value\":")) return 74;
      if (!lang_write_json_string("Go")) return 74;
      if (!lang_write_literal("},\"events\":[")) return 74;
      if (!lang_write_events()) return 74;
      if (!lang_write_literal("],\"live_resources\":[]}\n")) return 74;
      return 0;
    }
    case LANG_SIGNAL_LANG_HALT: {
      LANG_SIGNAL lang_value_flag_LANG_PLACE_4 = lang_value_flag; /* copy: s1:fallible.defect_terminal:fn:triage:op:3 */
      (void)lang_value_flag_LANG_PLACE_4;
      if (!lang_record_event("value.copied", "s1:fallible.defect_terminal:fn:triage:op:3:event", "s1:fallible.defect_terminal:fn:triage", "s1:fallible.defect_terminal:fn:triage:place:0", "s1:fallible.defect_terminal:fn:triage:place:4", "s1:fallible.defect_terminal:fn:triage:type:0")) return 74;
      if (!lang_write_literal("{\"schema\":\"lang.execution/1\",\"outcome\":{\"kind\":\"defect\",\"value\":\"\"},\"events\":[")) return 74;
      if (!lang_write_events()) return 74;
      if (lang_event_count != 0u && !lang_write_bytes(",", 1u)) return 74;
      if (!lang_write_literal("{\"schema\":\"lang.execution/1\",\"id\":")) return 74;
      if (!lang_write_json_string("s1:fallible.defect_terminal:fn:triage:op:4:event:defected")) return 74;
      if (!lang_write_literal(",\"kind\":\"function.defected\",\"function_id\":")) return 74;
      if (!lang_write_json_string("s1:fallible.defect_terminal:fn:triage")) return 74;
      if (!lang_write_literal(",\"source_place\":")) return 74;
      if (!lang_write_json_string("s1:fallible.defect_terminal:fn:triage:place:4")) return 74;
      if (!lang_write_literal(",\"type_id\":")) return 74;
      if (!lang_write_json_string("s1:fallible.defect_terminal:fn:triage:type:0")) return 74;
      if (!lang_write_literal(",\"output\":")) return 74;
      if (!lang_write_json_string("halt requested")) return 74;
      if (!lang_write_literal("}")) return 74;
      if (!lang_write_literal("],\"live_resources\":[]}\n")) return 74;
      lang_defect("halt requested");
      return 71; /* unreachable: lang_defect never returns */
    }
  }
  return 70; /* invalid safe-language tag: fail in main */
}
