/* generated by Codename Lang; schema lang.c17/0 */
#include <setjmp.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct _LANG_lang_res_open_result {
  unsigned char ok;
  unsigned char value;
} _LANG_lang_res_open_result;

extern _LANG_lang_res_open_result _LANG_lang_res_open(unsigned char argument);

jmp_buf lang_nonlocal_landing;

#define LANG_OUTPUT_LIMIT 65536u

static size_t lang_event_count = 0u;
static size_t lang_output_count = 0u;

static int lang_write_bytes(const char *data, size_t length) {
  if (length > LANG_OUTPUT_LIMIT - lang_output_count) return 0;
  if (length != 0u && fwrite(data, 1u, length, stdout) != length) return 0;
  lang_output_count += length;
  return 1;
}

static int lang_write_literal(const char *value) {
  return lang_write_bytes(value, strlen(value));
}

static int lang_write_json_string(const char *value) {
  static const char hex[] = "0123456789abcdef";
  if (!lang_write_bytes("\"", 1u)) return 0;
  for (; *value != '\0'; value++) {
    unsigned char byte = (unsigned char)*value;
    const char *escape = NULL;
    if (byte == '"') escape = "\\\"";
    else if (byte == '\\') escape = "\\\\";
    else if (byte == '\b') escape = "\\b";
    else if (byte == '\f') escape = "\\f";
    else if (byte == '\n') escape = "\\n";
    else if (byte == '\r') escape = "\\r";
    else if (byte == '\t') escape = "\\t";
    if (escape != NULL) { if (!lang_write_literal(escape)) return 0; }
    else if (byte < 0x20u) {
      char encoded[6] = {'\\', 'u', '0', '0', hex[byte >> 4u], hex[byte & 0x0fu]};
      if (!lang_write_bytes(encoded, sizeof encoded)) return 0;
    } else if (!lang_write_bytes(value, 1u)) return 0;
  }
  return lang_write_bytes("\"", 1u);
}

static int lang_record_event(const char *kind, const char *id, const char *function_id, const char *source_place, const char *target_place, const char *type_id) {
  if (lang_event_count != 0u && !lang_write_bytes(",", 1u)) return 0;
  lang_event_count++;
  if (!lang_write_literal("{\"schema\":\"lang.execution/1\",\"id\":") || !lang_write_json_string(id)) return 0;
  if (!lang_write_literal(",\"kind\":") || !lang_write_json_string(kind)) return 0;
  if (!lang_write_literal(",\"function_id\":") || !lang_write_json_string(function_id)) return 0;
  if (source_place != NULL && (!lang_write_literal(",\"source_place\":") || !lang_write_json_string(source_place))) return 0;
  if (target_place != NULL && (!lang_write_literal(",\"target_place\":") || !lang_write_json_string(target_place))) return 0;
  if (type_id != NULL && (!lang_write_literal(",\"type_id\":") || !lang_write_json_string(type_id))) return 0;
  return lang_write_bytes("}", 1u);
}

static int lang_write_byte(unsigned char value) {
  char encoded[3];
  int length = snprintf(encoded, sizeof encoded, "%u", (unsigned int)value);
  return length > 0 && (size_t)length < sizeof encoded && lang_write_bytes(encoded, (size_t)length);
}

static const char *lang_resource_ids[3] = {
  "s1:phase5.tail_collapse_release_ladder:fn:main:place:1",
  "s1:phase5.tail_collapse_release_ladder:fn:main:place:2",
  "s1:phase5.tail_collapse_release_ladder:fn:main:place:3",
};
static int lang_resource_live[3];

static int lang_write_live_resources(void) {
  size_t index; int first = 1;
  for (index = 0u; index < 3u; index++) {
    if (!lang_resource_live[index]) continue;
    if (!first && !lang_write_bytes(",", 1u)) return 0;
    first = 0;
    if (!lang_write_json_string(lang_resource_ids[index])) return 0;
  }
  return 1;
}

int main(int argc, char **argv) {
  if (argc != 2) return 64;
  if (strcmp(argv[1], "7") != 0) return 65;
  unsigned char lang_value_request = 7u;
  if (!lang_write_literal("{\"schema\":\"lang.execution/1\",\"events\":[")) return 74;
  if (setjmp(lang_nonlocal_landing) != 0) { /* lang:nonlocal-pad-site */
    if (!lang_record_event("foreign.nonlocal_exit", "s1:phase5.tail_collapse_release_ladder:fn:main:event:nonlocal_exit", "s1:phase5.tail_collapse_release_ladder:fn:main", NULL, NULL, NULL)) abort();
    if (lang_resource_live[0] && !lang_record_event("resource.leaked", "s1:phase5.tail_collapse_release_ladder:fn:main:event:leaked:0", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:1", NULL, NULL)) abort();
    if (lang_resource_live[1] && !lang_record_event("resource.leaked", "s1:phase5.tail_collapse_release_ladder:fn:main:event:leaked:1", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:2", NULL, NULL)) abort();
    if (lang_resource_live[2] && !lang_record_event("resource.leaked", "s1:phase5.tail_collapse_release_ladder:fn:main:event:leaked:2", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:3", NULL, NULL)) abort();
    if (!lang_write_bytes(",", 1u)) abort();
    if (!lang_write_literal("{\"schema\":\"lang.execution/1\",\"id\":")) abort();
    if (!lang_write_json_string("s1:phase5.tail_collapse_release_ladder:fn:main:event:nonlocal_defect")) abort();
    if (!lang_write_literal(",\"kind\":\"function.defected\",\"function_id\":")) abort();
    if (!lang_write_json_string("s1:phase5.tail_collapse_release_ladder:fn:main")) abort();
    if (!lang_write_literal(",\"source_place\":")) abort();
    if (!lang_write_json_string("s1:phase5.tail_collapse_release_ladder:fn:main:place:0")) abort();
    if (!lang_write_literal(",\"type_id\":")) abort();
    if (!lang_write_json_string("s1:phase5.tail_collapse_release_ladder:fn:main:type:0")) abort();
    if (!lang_write_literal(",\"output\":")) abort();
    if (!lang_write_json_string("foreign nonlocal exit detected at process-root landing pad")) abort();
    if (!lang_write_literal("}")) abort();
    if (!lang_write_literal("],\"outcome\":{\"kind\":\"defect\",\"value\":\"\"},\"live_resources\":[")) abort();
    if (!lang_write_live_resources()) abort();
    if (!lang_write_literal("]}\n")) abort();
    abort();
  } /* lang:nonlocal-pad-end */
  _LANG_lang_res_open_result lang_value_foreign_result_0 = _LANG_lang_res_open(lang_value_request); /* s1:phase5.tail_collapse_release_ladder:fn:main:op:0 */
  if (!lang_record_event("foreign.called", "s1:phase5.tail_collapse_release_ladder:fn:main:op:0:event", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:0", "s1:phase5.tail_collapse_release_ladder:fn:main:place:1", "s1:phase5.tail_collapse_release_ladder:fn:main:type:0")) return 74;
  if (!lang_value_foreign_result_0.ok) {
    if (!lang_record_event("function.failed", "s1:phase5.tail_collapse_release_ladder:fn:main:op:3:event:failed", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:4", NULL, "s1:phase5.tail_collapse_release_ladder:fn:main:type:1")) return 74;
    if (!lang_write_literal("],\"outcome\":{\"kind\":\"typed_failure\",\"value\":")) return 74;
    if (!lang_write_json_string("OpenFailed")) return 74;
    if (!lang_write_literal("},\"live_resources\":[")) return 74;
    if (!lang_write_live_resources()) return 74;
    if (!lang_write_literal("]}\n")) return 74;
    return 0;
  }
  lang_resource_live[0] = 1; /* lang:ledger-populate-site */
  unsigned char lang_value_a = lang_value_foreign_result_0.value;
  (void)lang_value_a;
  _LANG_lang_res_open_result lang_value_foreign_result_1 = _LANG_lang_res_open(lang_value_request); /* s1:phase5.tail_collapse_release_ladder:fn:main:op:1 */
  if (!lang_record_event("foreign.called", "s1:phase5.tail_collapse_release_ladder:fn:main:op:1:event", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:0", "s1:phase5.tail_collapse_release_ladder:fn:main:place:2", "s1:phase5.tail_collapse_release_ladder:fn:main:type:0")) return 74;
  if (!lang_value_foreign_result_1.ok) {
    if (!lang_record_event("resource.released", "s1:phase5.tail_collapse_release_ladder:fn:main:op:4:event", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:1", NULL, "s1:phase5.tail_collapse_release_ladder:fn:main:type:0")) return 74; lang_resource_live[0] = 0; /* lang:release-site */
    if (!lang_record_event("function.failed", "s1:phase5.tail_collapse_release_ladder:fn:main:op:5:event:failed", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:5", NULL, "s1:phase5.tail_collapse_release_ladder:fn:main:type:2")) return 74;
    if (!lang_write_literal("],\"outcome\":{\"kind\":\"typed_failure\",\"value\":")) return 74;
    if (!lang_write_json_string("OpenFailed")) return 74;
    if (!lang_write_literal("},\"live_resources\":[")) return 74;
    if (!lang_write_live_resources()) return 74;
    if (!lang_write_literal("]}\n")) return 74;
    return 0;
  }
  lang_resource_live[1] = 1; /* lang:ledger-populate-site */
  unsigned char lang_value_b = lang_value_foreign_result_1.value;
  (void)lang_value_b;
  _LANG_lang_res_open_result lang_value_foreign_result_2 = _LANG_lang_res_open(lang_value_request); /* s1:phase5.tail_collapse_release_ladder:fn:main:op:2 */
  if (!lang_record_event("foreign.called", "s1:phase5.tail_collapse_release_ladder:fn:main:op:2:event", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:0", "s1:phase5.tail_collapse_release_ladder:fn:main:place:3", "s1:phase5.tail_collapse_release_ladder:fn:main:type:0")) return 74;
  if (!lang_value_foreign_result_2.ok) {
    if (!lang_record_event("resource.released", "s1:phase5.tail_collapse_release_ladder:fn:main:op:6:event", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:2", NULL, "s1:phase5.tail_collapse_release_ladder:fn:main:type:0")) return 74; lang_resource_live[1] = 0; /* lang:release-site */
    if (!lang_record_event("resource.released", "s1:phase5.tail_collapse_release_ladder:fn:main:op:7:event", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:1", NULL, "s1:phase5.tail_collapse_release_ladder:fn:main:type:0")) return 74; lang_resource_live[0] = 0; /* lang:release-site */
    if (!lang_record_event("function.failed", "s1:phase5.tail_collapse_release_ladder:fn:main:op:8:event:failed", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:6", NULL, "s1:phase5.tail_collapse_release_ladder:fn:main:type:3")) return 74;
    if (!lang_write_literal("],\"outcome\":{\"kind\":\"typed_failure\",\"value\":")) return 74;
    if (!lang_write_json_string("OpenFailed")) return 74;
    if (!lang_write_literal("},\"live_resources\":[")) return 74;
    if (!lang_write_live_resources()) return 74;
    if (!lang_write_literal("]}\n")) return 74;
    return 0;
  }
  lang_resource_live[2] = 1; /* lang:ledger-populate-site */
  unsigned char lang_value_c = lang_value_foreign_result_2.value;
  (void)lang_value_c;
  if (!lang_record_event("resource.released", "s1:phase5.tail_collapse_release_ladder:fn:main:op:9:event", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:3", NULL, "s1:phase5.tail_collapse_release_ladder:fn:main:type:0")) return 74; lang_resource_live[2] = 0; /* lang:release-site */
  if (!lang_record_event("resource.released", "s1:phase5.tail_collapse_release_ladder:fn:main:op:10:event", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:2", NULL, "s1:phase5.tail_collapse_release_ladder:fn:main:type:0")) return 74; lang_resource_live[1] = 0; /* lang:release-site */
  if (!lang_record_event("resource.released", "s1:phase5.tail_collapse_release_ladder:fn:main:op:11:event", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:1", NULL, "s1:phase5.tail_collapse_release_ladder:fn:main:type:0")) return 74; lang_resource_live[0] = 0; /* lang:release-site */
  if (!lang_record_event("function.returned", "s1:phase5.tail_collapse_release_ladder:fn:main:op:12:event:returned", "s1:phase5.tail_collapse_release_ladder:fn:main", "s1:phase5.tail_collapse_release_ladder:fn:main:place:0", NULL, "s1:phase5.tail_collapse_release_ladder:fn:main:type:0")) return 74; /* returned place: s1:phase5.tail_collapse_release_ladder:fn:main:op:12 */
  if (!lang_write_literal("],\"outcome\":{\"kind\":\"returned\",\"value\":\"")) return 74;
  if (!lang_write_byte(lang_value_request)) return 74;
  if (!lang_write_literal("\"},\"live_resources\":[")) return 74;
  if (!lang_write_live_resources()) return 74;
  if (!lang_write_literal("]}\n")) return 74;
  return 0;
}
