/* generated by Codename Lang; schema lang.c17/0 */
#include <stdio.h>
#include <string.h>

typedef enum LANG_TYPE_0 {
  LANG_ALTERNATIVE_0 = 0,
  LANG_ALTERNATIVE_1 = 1,
} LANG_TYPE_0;

static LANG_TYPE_0 lang_function_0(LANG_TYPE_0 lang_place_0) {
  switch (lang_place_0) {
    case LANG_ALTERNATIVE_0: return LANG_ALTERNATIVE_1;
    case LANG_ALTERNATIVE_1: return LANG_ALTERNATIVE_0;
  }
  return (int)255; /* invalid safe-language tag: fail in main */
}

static const char *lang_type_0_name(LANG_TYPE_0 value) {
  switch (value) {
    case LANG_ALTERNATIVE_0: return "Off";
    case LANG_ALTERNATIVE_1: return "On";
  }
  return NULL;
}

int main(int argc, char **argv) {
  if (argc != 2) return 64;
  LANG_TYPE_0 input;
  if (strcmp(argv[1], "Off") == 0) input = LANG_ALTERNATIVE_0;
  else if (strcmp(argv[1], "On") == 0) input = LANG_ALTERNATIVE_1;
  else return 65;
  LANG_TYPE_0 output = lang_function_0(input);
  const char *name = lang_type_0_name(output);
  if (name == NULL) return 70;
  printf("%s\n", name);
  return 0;
}
