/* generated by Codename Lang; schema lang.c17/0 */
/* Moves below are authority transitions; C value assignment makes no ABI or zero-copy claim. */
/* call-boundary attribute set: EMPTY (0 entries). Per D-11-09, cgen.emitCall never mints an optimizer-visible alias or capture attribute at any Lang-to-Lang call boundary this phase -- NAT-05 is satisfied by this explicit, generated empty set, not by silence. */
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char *lang_invocations[] = {
  "inv:entry:s1:examples.switch:fn:toggle",
};

typedef enum LANG_SWITCH {
  LANG_SWITCH_LANG_OFF = 0,
  LANG_SWITCH_LANG_ON = 1,
} LANG_SWITCH;

static const char *LANG_SWITCH_name(LANG_SWITCH value) {
  switch (value) {
    case LANG_SWITCH_LANG_OFF: return "Off";
    case LANG_SWITCH_LANG_ON: return "On";
  }
  return NULL;
}

#define LANG_OUTPUT_LIMIT 16777216u
#define LANG_EVENT_CAPACITY 1u

typedef struct LANG_EVENT {
  const char *kind;
  const char *id;
  const char *function_id;
  const char *source_place;
  const char *target_place;
  const char *type_id;
  const char *invocation;
  const char *callee_function_id;
} LANG_EVENT;

static LANG_EVENT lang_events[LANG_EVENT_CAPACITY];
static size_t lang_event_count = 0u;
static size_t lang_output_count = 0u;

static int lang_write_bytes(const char *data, size_t length) {
  if (length > LANG_OUTPUT_LIMIT - lang_output_count) return 0;
  if (length != 0u && fwrite(data, 1u, length, stdout) != length) return 0;
  lang_output_count += length;
  return 1;
}

static int lang_write_literal(const char *value) {
  return lang_write_bytes(value, strlen(value));
}

static int lang_write_json_string(const char *value) {
  static const char hex[] = "0123456789abcdef";
  if (!lang_write_bytes("\"", 1u)) return 0;
  for (; *value != '\0'; value++) {
    unsigned char byte = (unsigned char)*value;
    const char *escape = NULL;
    if (byte == '"') escape = "\\\"";
    else if (byte == '\\') escape = "\\\\";
    else if (byte == '\b') escape = "\\b";
    else if (byte == '\f') escape = "\\f";
    else if (byte == '\n') escape = "\\n";
    else if (byte == '\r') escape = "\\r";
    else if (byte == '\t') escape = "\\t";
    if (escape != NULL) { if (!lang_write_literal(escape)) return 0; }
    else if (byte < 0x20u) {
      char encoded[6] = {'\\', 'u', '0', '0', hex[byte >> 4u], hex[byte & 0x0fu]};
      if (!lang_write_bytes(encoded, sizeof encoded)) return 0;
    } else if (!lang_write_bytes(value, 1u)) return 0;
  }
  return lang_write_bytes("\"", 1u);
}

static int lang_record_event(const char *kind, const char *id, const char *function_id, const char *source_place, const char *target_place, const char *type_id, const char *invocation, const char *callee_function_id) {
  if (lang_event_count >= LANG_EVENT_CAPACITY) return 0;
  lang_events[lang_event_count++] = (LANG_EVENT){kind, id, function_id, source_place, target_place, type_id, invocation, callee_function_id};
  return 1;
}

static int lang_write_events(void) {
  size_t index;
  for (index = 0u; index < lang_event_count; index++) {
    const LANG_EVENT *event = &lang_events[index];
    if (index != 0u && !lang_write_bytes(",", 1u)) return 0;
    if (!lang_write_literal("{\"schema\":\"lang.execution/2\",\"id\":") || !lang_write_json_string(event->id)) return 0;
    if (!lang_write_literal(",\"kind\":") || !lang_write_json_string(event->kind)) return 0;
    if (!lang_write_literal(",\"function_id\":") || !lang_write_json_string(event->function_id)) return 0;
    if (event->source_place != NULL && (!lang_write_literal(",\"source_place\":") || !lang_write_json_string(event->source_place))) return 0;
    if (event->target_place != NULL && (!lang_write_literal(",\"target_place\":") || !lang_write_json_string(event->target_place))) return 0;
    if (event->type_id != NULL && (!lang_write_literal(",\"type_id\":") || !lang_write_json_string(event->type_id))) return 0;
    if (!lang_write_literal(",\"invocation\":") || !lang_write_json_string(event->invocation)) return 0;
    if (event->callee_function_id != NULL && (!lang_write_literal(",\"callee_function_id\":") || !lang_write_json_string(event->callee_function_id))) return 0;
    if (!lang_write_bytes("}", 1u)) return 0;
  }
  return 1;
}

static int lang_write_live_resources(void) {
  return lang_write_literal("[]");
}

static LANG_SWITCH LANG_TOGGLE(LANG_SWITCH, unsigned int);

static LANG_SWITCH LANG_TOGGLE(LANG_SWITCH value, unsigned int invocation_index) {
  switch (value) {
    case LANG_SWITCH_LANG_OFF:
      if (!lang_record_event("function.returned", "s1:examples.switch:fn:toggle:match:return", "s1:examples.switch:fn:toggle", "s1:examples.switch:parameter:toggle.state", NULL, "Switch", lang_invocations[invocation_index], NULL)) abort();
      return LANG_SWITCH_LANG_ON;
    case LANG_SWITCH_LANG_ON:
      if (!lang_record_event("function.returned", "s1:examples.switch:fn:toggle:match:return", "s1:examples.switch:fn:toggle", "s1:examples.switch:parameter:toggle.state", NULL, "Switch", lang_invocations[invocation_index], NULL)) abort();
      return LANG_SWITCH_LANG_OFF;
  }
  abort();
}

int main(int argc, char **argv) {
  (void)lang_invocations;
  (void)lang_record_event;
  (void)LANG_TOGGLE;
  if (argc != 2) return 64;
  LANG_SWITCH lang_entry_input;
  if (strcmp(argv[1], "Off") == 0) lang_entry_input = LANG_SWITCH_LANG_OFF;
  else if (strcmp(argv[1], "On") == 0) lang_entry_input = LANG_SWITCH_LANG_ON;
  else return 65;
  LANG_SWITCH lang_entry_output = LANG_TOGGLE(lang_entry_input, 0u);
  const char *lang_entry_name = LANG_SWITCH_name(lang_entry_output);
  if (lang_entry_name == NULL) return 70;
  if (!lang_write_literal("{\"schema\":\"lang.execution/2\",\"outcome\":{\"kind\":\"returned\",\"value\":")) return 74;
  if (!lang_write_json_string(lang_entry_name)) return 74;
  if (!lang_write_literal("},\"events\":[")) return 74;
  if (!lang_write_events()) return 74;
  if (!lang_write_literal("],\"live_resources\":")) return 74;
  if (!lang_write_live_resources()) return 74;
  if (!lang_write_literal("}\n")) return 74;
  return 0;
}
