/* generated by Schway; schema lang.c17/0 */
/* Moves below are authority transitions; C value assignment makes no ABI or zero-copy claim. */
/* call-boundary attribute set: EMPTY (0 entries). Per D-11-09, cgen.emitCall never mints an optimizer-visible alias or capture attribute at any Lang-to-Lang call boundary this phase -- NAT-05 is satisfied by this explicit, generated empty set, not by silence. */
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char *schway_invocations[] = {
  "inv:entry:s1:owned.transfer:fn:relay",
};

typedef struct SCHWAY_BUFFER {
  unsigned char bytes[4];
  size_t length;
} SCHWAY_BUFFER;

#define SCHWAY_OUTPUT_LIMIT 16777216u
#define SCHWAY_EVENT_CAPACITY 2u

typedef struct SCHWAY_EVENT {
  const char *kind;
  const char *id;
  const char *function_id;
  const char *source_place;
  const char *target_place;
  const char *type_id;
  const char *invocation;
  const char *callee_function_id;
} SCHWAY_EVENT;

static SCHWAY_EVENT schway_events[SCHWAY_EVENT_CAPACITY];
static size_t schway_event_count = 0u;
static size_t schway_output_count = 0u;

static int schway_write_bytes(const char *data, size_t length) {
  if (length > SCHWAY_OUTPUT_LIMIT - schway_output_count) return 0;
  if (length != 0u && fwrite(data, 1u, length, stdout) != length) return 0;
  schway_output_count += length;
  return 1;
}

static int schway_write_literal(const char *value) {
  return schway_write_bytes(value, strlen(value));
}

static int schway_write_json_string(const char *value) {
  static const char hex[] = "0123456789abcdef";
  if (!schway_write_bytes("\"", 1u)) return 0;
  for (; *value != '\0'; value++) {
    unsigned char byte = (unsigned char)*value;
    const char *escape = NULL;
    if (byte == '"') escape = "\\\"";
    else if (byte == '\\') escape = "\\\\";
    else if (byte == '\b') escape = "\\b";
    else if (byte == '\f') escape = "\\f";
    else if (byte == '\n') escape = "\\n";
    else if (byte == '\r') escape = "\\r";
    else if (byte == '\t') escape = "\\t";
    if (escape != NULL) { if (!schway_write_literal(escape)) return 0; }
    else if (byte < 0x20u) {
      char encoded[6] = {'\\', 'u', '0', '0', hex[byte >> 4u], hex[byte & 0x0fu]};
      if (!schway_write_bytes(encoded, sizeof encoded)) return 0;
    } else if (!schway_write_bytes(value, 1u)) return 0;
  }
  return schway_write_bytes("\"", 1u);
}

static int schway_record_event(const char *kind, const char *id, const char *function_id, const char *source_place, const char *target_place, const char *type_id, const char *invocation, const char *callee_function_id) {
  if (schway_event_count >= SCHWAY_EVENT_CAPACITY) return 0;
  schway_events[schway_event_count++] = (SCHWAY_EVENT){kind, id, function_id, source_place, target_place, type_id, invocation, callee_function_id};
  return 1;
}

static int schway_write_events(void) {
  size_t index;
  for (index = 0u; index < schway_event_count; index++) {
    const SCHWAY_EVENT *event = &schway_events[index];
    if (index != 0u && !schway_write_bytes(",", 1u)) return 0;
    if (!schway_write_literal("{\"schema\":\"lang.execution/2\",\"id\":") || !schway_write_json_string(event->id)) return 0;
    if (!schway_write_literal(",\"kind\":") || !schway_write_json_string(event->kind)) return 0;
    if (!schway_write_literal(",\"function_id\":") || !schway_write_json_string(event->function_id)) return 0;
    if (event->source_place != NULL && (!schway_write_literal(",\"source_place\":") || !schway_write_json_string(event->source_place))) return 0;
    if (event->target_place != NULL && (!schway_write_literal(",\"target_place\":") || !schway_write_json_string(event->target_place))) return 0;
    if (event->type_id != NULL && (!schway_write_literal(",\"type_id\":") || !schway_write_json_string(event->type_id))) return 0;
    if (!schway_write_literal(",\"invocation\":") || !schway_write_json_string(event->invocation)) return 0;
    if (event->callee_function_id != NULL && (!schway_write_literal(",\"callee_function_id\":") || !schway_write_json_string(event->callee_function_id))) return 0;
    if (!schway_write_bytes("}", 1u)) return 0;
  }
  return 1;
}

static int schway_write_buffer_hex(const SCHWAY_BUFFER *value) {
  static const char hex[] = "0123456789abcdef";
  size_t index;
  if (value->length > sizeof value->bytes) return 0;
  for (index = 0u; index < value->length; index++) {
    char encoded[2] = {hex[value->bytes[index] >> 4u], hex[value->bytes[index] & 0x0fu]};
    if (!schway_write_bytes(encoded, sizeof encoded)) return 0;
  }
  return 1;
}

static int schway_write_live_resources(void) {
  return schway_write_literal("[]");
}

static SCHWAY_BUFFER SCHWAY_RELAY(SCHWAY_BUFFER, unsigned int);

static SCHWAY_BUFFER SCHWAY_RELAY(SCHWAY_BUFFER schway_value_buffer, unsigned int invocation_index) {
  (void)invocation_index;
  SCHWAY_BUFFER schway_value_delivered = schway_value_buffer; /* authority transfer: s1:owned.transfer:fn:relay:op:0 */ /* schway:mutation-site */
  (void)schway_value_delivered;
  if (!schway_record_event("value.transferred", "s1:owned.transfer:fn:relay:op:0:event", "s1:owned.transfer:fn:relay", "s1:owned.transfer:fn:relay:place:0", "s1:owned.transfer:fn:relay:place:1", "s1:owned.transfer:fn:relay:type:0", schway_invocations[invocation_index], NULL)) abort();
  if (!schway_record_event("function.returned", "s1:owned.transfer:fn:relay:op:1:event:returned", "s1:owned.transfer:fn:relay", "s1:owned.transfer:fn:relay:place:1", NULL, "s1:owned.transfer:fn:relay:type:0", schway_invocations[invocation_index], NULL)) abort(); /* returned place: s1:owned.transfer:fn:relay:op:1 */
  return schway_value_delivered;
}

int main(int argc, char **argv) {
  (void)schway_invocations;
  (void)schway_record_event;
  (void)SCHWAY_RELAY;
  (void)schway_write_buffer_hex;
  if (argc != 2) return 64;
  if (strcmp(argv[1], "01020304") != 0) return 65;
  SCHWAY_BUFFER schway_entry_input = {{1u, 2u, 3u, 4u}, 4u};
  SCHWAY_BUFFER schway_entry_output = SCHWAY_RELAY(schway_entry_input, 0u);
  if (!schway_write_literal("{\"schema\":\"lang.execution/2\",\"outcome\":{\"kind\":\"returned\",\"value\":\"")) return 74;
  if (!schway_write_buffer_hex(&schway_entry_output)) return 74;
  if (!schway_write_literal("\"},\"events\":[")) return 74;
  if (!schway_write_events()) return 74;
  if (!schway_write_literal("],\"live_resources\":")) return 74;
  if (!schway_write_live_resources()) return 74;
  if (!schway_write_literal("}\n")) return 74;
  return 0;
}
