/* generated by Codename Lang; schema lang.c17/0 */
/* Moves below are authority transitions; C value assignment makes no ABI or zero-copy claim. */
#include <stddef.h>
#include <stdio.h>
#include <string.h>

typedef struct LANG_BUFFER {
  unsigned char bytes[4];
  size_t length;
} LANG_BUFFER;

int main(int argc, char **argv) {
  if (argc != 2) return 64;
  if (strcmp(argv[1], "01020304") != 0) return 65;
  LANG_BUFFER lang_value_buffer = {{1u, 2u, 3u, 4u}, 4u};
  LANG_BUFFER lang_value_delivered = lang_value_buffer; /* authority transfer: s1:owned.transfer:fn:relay:op:0 */
  (void)lang_value_delivered; /* returned place: s1:owned.transfer:fn:relay:op:1 */
  puts("{\"schema\":\"lang.execution/1\",\"outcome\":{\"kind\":\"returned\",\"value\":\"01020304\"},\"events\":[{\"schema\":\"lang.execution/1\",\"id\":\"s1:owned.transfer:fn:relay:op:0:event\",\"kind\":\"value.transferred\",\"function_id\":\"s1:owned.transfer:fn:relay\",\"source_place\":\"s1:owned.transfer:fn:relay:place:0\",\"target_place\":\"s1:owned.transfer:fn:relay:place:1\",\"type_id\":\"s1:owned.transfer:fn:relay:type:0\"},{\"schema\":\"lang.execution/1\",\"id\":\"s1:owned.transfer:fn:relay:op:1:event:returned\",\"kind\":\"function.returned\",\"function_id\":\"s1:owned.transfer:fn:relay\",\"source_place\":\"s1:owned.transfer:fn:relay:place:1\",\"type_id\":\"s1:owned.transfer:fn:relay:type:0\"}],\"live_resources\":[]}");
  return 0;
}
